// @generated by protoc-gen-ts-contract v0.1.4 with parameter "target=ts,import_extension=.js"
// @generated from file fixtures/orders/v1/order.proto (package fixtures.orders.v1, syntax proto3)
/* eslint-disable */

import type { MoneyInput } from "../../common/v1/common_contract.js";
import type { Status } from "../../common/v1/common_pb.js";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

export interface OrderInput {
  id: string;
  total?: MoneyInput;
  lines?: OrderLineInput[];
  attributes?: Record<string, string>;
  status?: Status;
  placedAt?: Timestamp;
}

export interface OrderLineInput {
  sku: string;
  quantity?: number;
}

export interface WrappedInput {
  inner?: Wrapped_InnerInput;
}

export interface Wrapped_InnerInput {
  label?: string;
}
