// @generated by protoc-gen-es v2.0.0 with parameter "target=ts,import_extension=.js"
// @generated from file fixtures/orders/v1/order.proto (package fixtures.orders.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb.js";
import type { Money, Status } from "../../common/v1/common_pb.js";
import { file_fixtures_common_v1_common } from "../../common/v1/common_pb.js";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file fixtures/orders/v1/order.proto.
 */
export const file_fixtures_orders_v1_order: GenFile = /*@__PURE__*/
  fileDesc("Ch5maXh0dXJlcy9vcmRlcnMvdjEvb3JkZXIucHJvdG8SEmZpeHR1cmVzLm9yZGVycy52MSIyCglPcmRlckxpbmUSEwoDc2t1GAEgASgJQga6SAPIAQESEAoIcXVhbnRpdHkYAiABKA0iwAIKBU9yZGVyEhIKAmlkGAEgASgJQga6SAPIAQESKAoFdG90YWwYAiABKAsyGS5maXh0dXJlcy5jb21tb24udjEuTW9uZXkSLAoFbGluZXMYAyADKAsyHS5maXh0dXJlcy5vcmRlcnMudjEuT3JkZXJMaW5lEj0KCmF0dHJpYnV0ZXMYBCADKAsyKS5maXh0dXJlcy5vcmRlcnMudjEuT3JkZXIuQXR0cmlidXRlc0VudHJ5EioKBnN0YXR1cxgFIAEoDjIaLmZpeHR1cmVzLmNvbW1vbi52MS5TdGF0dXMSLQoJcGxhY2VkX2F0GAYgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBoxCg9BdHRyaWJ1dGVzRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4ASJxCgdXcmFwcGVkEjAKBWlubmVyGAEgASgLMiEuZml4dHVyZXMub3JkZXJzLnYxLldyYXBwZWQuSW5uZXISEQoHaWdub3JlZBgCIAEoCUgAGhYKBUlubmVyEg0KBWxhYmVsGAEgASgJQgkKB3NraXBwZWRiBnByb3RvMw", [file_buf_validate_validate, file_fixtures_common_v1_common, file_google_protobuf_timestamp]);

/**
 * @generated from message fixtures.orders.v1.OrderLine
 */
export type OrderLine = Message<"fixtures.orders.v1.OrderLine"> & {
  /**
   * @generated from field: string sku = 1;
   */
  sku: string;

  /**
   * @generated from field: uint32 quantity = 2;
   */
  quantity: number;
};

/**
 * Describes the message fixtures.orders.v1.OrderLine.
 * Use `create(OrderLineSchema)` to create a new message.
 */
export const OrderLineSchema: GenMessage<OrderLine> = /*@__PURE__*/
  messageDesc(file_fixtures_orders_v1_order, 0);

/**
 * @generated from message fixtures.orders.v1.Order
 */
export type Order = Message<"fixtures.orders.v1.Order"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: fixtures.common.v1.Money total = 2;
   */
  total?: Money;

  /**
   * @generated from field: repeated fixtures.orders.v1.OrderLine lines = 3;
   */
  lines: OrderLine[];

  /**
   * @generated from field: map<string, string> attributes = 4;
   */
  attributes: { [key: string]: string };

  /**
   * @generated from field: fixtures.common.v1.Status status = 5;
   */
  status: Status;

  /**
   * @generated from field: google.protobuf.Timestamp placed_at = 6;
   */
  placedAt?: Timestamp;
};

/**
 * Describes the message fixtures.orders.v1.Order.
 * Use `create(OrderSchema)` to create a new message.
 */
export const OrderSchema: GenMessage<Order> = /*@__PURE__*/
  messageDesc(file_fixtures_orders_v1_order, 1);

/**
 * @generated from message fixtures.orders.v1.Wrapped
 */
export type Wrapped = Message<"fixtures.orders.v1.Wrapped"> & {
  /**
   * @generated from field: fixtures.orders.v1.Wrapped.Inner inner = 1;
   */
  inner?: Wrapped_Inner;

  /**
   * @generated from oneof fixtures.orders.v1.Wrapped.skipped
   */
  skipped: {
    /**
     * @generated from field: string ignored = 2;
     */
    value: string;
    case: "ignored";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message fixtures.orders.v1.Wrapped.
 * Use `create(WrappedSchema)` to create a new message.
 */
export const WrappedSchema: GenMessage<Wrapped> = /*@__PURE__*/
  messageDesc(file_fixtures_orders_v1_order, 2);

/**
 * @generated from message fixtures.orders.v1.Wrapped.Inner
 */
export type Wrapped_Inner = Message<"fixtures.orders.v1.Wrapped.Inner"> & {
  /**
   * @generated from field: string label = 1;
   */
  label: string;
};

/**
 * Describes the message fixtures.orders.v1.Wrapped.Inner.
 * Use `create(Wrapped_InnerSchema)` to create a new message.
 */
export const Wrapped_InnerSchema: GenMessage<Wrapped_Inner> = /*@__PURE__*/
  messageDesc(file_fixtures_orders_v1_order, 2, 0);

