// @generated by protoc-gen-ts-contract v0.1.3 with parameter "target=ts,import_extension=.js"
// @generated from file fixtures/common/v1/common.proto (package fixtures.common.v1, syntax proto3)
/* eslint-disable */

export interface MoneyInput {
  amount: bigint;
  currency: string;
}
